### ISSUE TITLE
Error 500 during logging in

### ISSUE THREAD

**Issue by Warent2454** [add-ons/plugin.video.vtm.go#173]
Hi first of all thank you for creating this addon.
I am experiencing an issue with it. After installing and providing a valid login. The addons show 'error 500' and then just keeps loading.
I did notice i am missing a dependance 'script.module.win_inet_pton' but i cant seem to install that.
I have the issue on an android phone and a ubuntu install.

Kodi: 18.6
addon Version 1.01

Thanks for your help!

**Comment by michaelarnauts** [comment]
Can you look in the Kodi log and provide the full error?

Are you able to login in the VTM go website itself and play something there?

**Comment by Warent2454** [comment]
The log:

`2020-05-01 09:51:41.779 T:8924   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.Exception'>
                                            Error Contents: Error 500.
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vtm.go/service.py", line 8, in <module>
                                                service.run()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vtm.go/resources/lib/service.py", line 73, in run
                                                BackgroundService().run()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vtm.go/resources/lib/service.py", line 33, in run
                                                self._update_metadata()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vtm.go/resources/lib/service.py", line 64, in _update_metadata
                                                success = Metadata(self.kodi).fetch_metadata(callback=update_status)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vtm.go/resources/lib/modules/metadata.py", line 39, in fetch_metadata
                                                items = self._vtm_go.get_items()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vtm.go/resources/lib/vtmgo/vtmgo.py", line 486, in get_items
                                                response = self._get_url('/%s/catalog' % self._mode(), {'pageSize': 1000})
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vtm.go/resources/lib/vtmgo/vtmgo.py", line 752, in _get_url
                                                token = self._auth.get_token()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vtm.go/resources/lib/vtmgo/vtmgoauth.py", line 86, in get_token
                                                self._token = self._login()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vtm.go/resources/lib/vtmgo/vtmgoauth.py", line 166, in _login
                                                raise Exception('Error %s.' % response.status_code)
                                            Exception: Error 500.
                                            -->End of Python script error report<--
2020-05-01 09:51:49.432 T:8914   ERROR: DoWork - Direct texture file loading failed for androidapp://sources/apps/com.kevinforeman.nzb360.png
2020-05-01 09:51:49.432 T:8906   ERROR: DoWork - Direct texture file loading failed for androidapp://sources/apps/de.zalando.mobile.png
2020-05-01 09:51:49.433 T:8991   ERROR: DoWork - Direct texture file loading failed for androidapp://sources/apps/org.jitsi.meet.png
2020-05-01 09:51:49.441 T:8915   ERROR: DoWork - Direct texture file loading failed for androidapp://sources/apps/com.skype.raider.png
2020-05-01 09:51:49.446 T:8906   ERROR: DoWork - Direct texture file loading failed for androidapp://sources/apps/com.google.android.youtube.png
2020-05-01 09:52:13.655 T:9004   ERROR: GetDirectory - Error getting plugin://plugin.video.vtm.go/
2020-05-01 09:52:13.658 T:8862   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vtm.go/) failed
2020-05-01 09:52:17.015 T:8862  NOTICE: CWinSystemAndroid::DestroyWindow
2020-05-01 09:52:17.144 T:8817 WARNING: CPeripheralBusAndroid: failed to update input device with ID 6 because it couldn't be found
'

Yes we can use the android or ios app without issues.

**Comment by KaleidoCR** [comment]
Hello,
Also, thanks for your efforts!
I am also experiencing Error 500. Credentials are ok and work on the website.

Fresh install on a raspberry pi 4B, running retropie + kodi 18.6 with inputstream adaptive 2.4.4

got this from the error log:

`2020-05-01 15:54:22.154 T:2676646096   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.Exception'>
                                            Error Contents: Error 500.
                                            Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/plugin.video.vtm.go/service.py", line 8, in <module>
                                                service.run()
                                              File "/home/pi/.kodi/addons/plugin.video.vtm.go/resources/lib/service.py", line 73, in run
                                                BackgroundService().run()
                                              File "/home/pi/.kodi/addons/plugin.video.vtm.go/resources/lib/service.py", line 33, in run
                                                self._update_metadata()
                                              File "/home/pi/.kodi/addons/plugin.video.vtm.go/resources/lib/service.py", line 64, in _update_metadata
                                                success = Metadata(self.kodi).fetch_metadata(callback=update_status)
                                              File "/home/pi/.kodi/addons/plugin.video.vtm.go/resources/lib/modules/metadata.py", line 39, in fetch_metadata
                                                items = self._vtm_go.get_items()
                                              File "/home/pi/.kodi/addons/plugin.video.vtm.go/resources/lib/vtmgo/vtmgo.py", line 486, in get_items
                                                response = self._get_url('/%s/catalog' % self._mode(), {'pageSize': 1000})
                                              File "/home/pi/.kodi/addons/plugin.video.vtm.go/resources/lib/vtmgo/vtmgo.py", line 752, in _get_url
                                                token = self._auth.get_token()
                                              File "/home/pi/.kodi/addons/plugin.video.vtm.go/resources/lib/vtmgo/vtmgoauth.py", line 86, in get_token
                                                self._token = self._login()
                                              File "/home/pi/.kodi/addons/plugin.video.vtm.go/resources/lib/vtmgo/vtmgoauth.py", line 166, in _login
                                                raise Exception('Error %s.' % response.status_code)
                                            Exception: Error 500.
                                            -->End of Python script error report<--
`

**Comment by michaelarnauts** [comment]
Can you try if this zip fixes your problem?

[plugin.video.vtm.go-1.0.1-auth-flow-75b0d02.zip](https://github.com/add-ons/plugin.video.vtm.go/files/4565928/plugin.video.vtm.go-1.0.1-auth-flow-75b0d02.zip)

**Comment by Warent2454** [comment]
Hi michael,

This seems to fix the issue on my android. I will test later on my Ubuntu if i have access to it.
Thanks for a fix!

**Comment by michaelarnauts** [comment]
@KaleidoCR can you also verify if this fixes your problem? I can then release an updated version so it's fixed for everyone.

**Comment by Warent2454** [comment]
It seems it is also fixed on my ubuntu htpc. My wife is very happy thanks!

**Comment by KaleidoCR** [comment]
Hello Michael,
I wasn't expecting such a quick reply, wow!
I will be able to test it later today and get back to you. my raspi is running lengthy updates atm.
Warent2454's results are very hopeful! (fingers crossed)

**Comment by KaleidoCR** [comment]
@michaelarnauts I'm happy to report your update fixed the issue for me as well.
Thanks so much for the quick response and great support! Have a nice weekend :)

**Comment by michaelarnauts** [comment]
Okay. The fix has been already submitted to the Kodi repository, so you will get an automatic update soon.

**Comment by zegmaarmanu** [comment]
TOP!
