### ISSUE TITLE
Playback failed

### ISSUE THREAD

**Issue by billgoldbergmania** [add-ons/plugin.video.vtm.go#202]
**Describe the bug**
Playback failed on all videos in the addon, including live streams.

**To Reproduce**
1. Try to watch video
2. Playback failed: one or more items failed to play, check the log for more information

**Expected behavior**
Play the video

**Screenshots**
https://imgur.com/a/iMnhBeC

**System**
 - Addon version: 1.1.0
 - Kodi version: 18.7
 - Inputstream adaptive version: 2.4.4
 - Operating System: Raspbian 
 - Special Hardware: Raspberry Pi 3

**Additional context**
Used to work fine, stopped working completely now for a few weeks. Might have updated the addon, not sure.

**Comment by michaelarnauts** [comment]
Can you also provide the relevant kodi.log lines?

**Comment by mediaminister** [comment]
A reboot is needed when updating InputStream Adaptive: https://github.com/peak3d/inputstream.adaptive/issues/454

**Comment by billgoldbergmania** [comment]
> Can you also provide the relevant kodi.log lines?

`2020-08-27 19:11:04.984 T:1407733984  NOTICE: [script.module.inputstreamhelper] Widevine update check was made on 2020-08-16 19:19
2020-08-27 19:11:06.271 T:1407733984   ERROR: [plugin.video.vtm.go] [vtmgostream] No manifest url found at https://dcs-live.apis.anvato.net/server/play/nzq4mI2owEdun8GGa/manifest.mpd?encp=fThQCWTGKtqbuq1_69h5XQ:zj3vwRcYYt-OsHq46aLglZL_meyHTGOpM14BCPWZexsor-Racn8FOMHUXmkwAY_7sfccDnbYGwq7dy3R_4jyTZvFKd_5LGvZuBGbsAU5R7dvHRY9pJ2NbzVpxvoj42XGo98TqfEE1b4Z4m528vd9ujQ6swF4RVR0gwOcFzV_8L1M8s9-eu2orXVaWEzRHSnyDfzlpzPEzYRJTaq2cqXMKIlBmcoJWXqkKd5yUuw-ga_9VOJt1XMY6KJkxSJBNHVqLYiFjOESJhGyqLeyqCdNuopuSX4N9xUrn7niXoHJEEo90bk4c0oF5s_bi8Tjfcc8RouwWzPG3ZgGysDqKaABE0jm6IDwOLGEm3UeoySHG0A4hfxE-ZnfhS4TN9dTD6Xl59WLgT-QgqrkV_ehGQilqTDE_Akc_-RJfZ_fZUM1LQkO5eRJIW1uUt-lEuw5e_mo0jtD3dpZgP34G-Tx_L2OOQJbW_af_Oy_gMf71fAStbZIlWo6XabSf_vCTjY2cxCAo1_gwrs2SRHPmY_anUKlz7ytVhuYegh86x3c0zVgkx3dTv074I8G_gYsdqovurTHH8aPFFUkhSIcWpzRTQ89FJuRKvBRpv9Lsk-5xMng6oMB-M7Q3zg7xmWihF56HMgDAra4lorr1r86Y0F_KZnpVBO__K20vJ5PbMdeQzfugAVWd4h5X8Mne_Q1iF8OGwtNHRVsOicaCLl5tMs7_4AUyvJhlamK8HunA-qSuAgxIYkp8Lm8QmrJZLLUyujLiDKwb6tbdIaaN3dgSDCXUd7kCaKTIya6zaObTmakV7vyAGzYA0u_PL2iqUuJpbVkGXPW2FpugVFTTIwYYrPJNBHu20xMXov-t9ymN25oQVVuXmigXiixbpElN7eO83pOZFHOwvkHNtTU5kQibpur3cxvd7LtGgB7mfIMYqArobYJ2IqoenAHpBJLj3pRPviByXeX_mT70h89eJBbCam_u0PSfmOB739tOMc-GBMdGGt486I&anvtrid=7wrUE5Q7BYhC4RwrTCeGR6JtWsHNNfoz&anvauth=tb=0~te=1598548355~sgn=978b5e540e97c0e8d2a733f6caaf54248d7bfc96155d0816e8c120759c182bf7&t=1598548265
2020-08-27 19:11:06.428 T:1407733984   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'ascii' codec can't decode byte 0xc3 in position 35: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/plugin.video.vtm.go/plugin.py", line 18, in <module>
                                                plugin.run(sys.argv)
                                              File "/home/pi/.kodi/addons/plugin.video.vtm.go/resources/lib/plugin.py", line 218, in run
                                                routing.run(params)
                                              File "/home/pi/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                self._dispatch(self.path)
                                              File "/home/pi/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                view_func(**kwargs)
                                              File "/home/pi/.kodi/addons/plugin.video.vtm.go/resources/lib/plugin.py", line 199, in play
                                                Player(kodi).play(category, item)
                                              File "/home/pi/.kodi/addons/plugin.video.vtm.go/resources/lib/modules/player.py", line 59, in play
                                                resolved_stream = self._vtm_go_stream.get_stream(category, item)
                                              File "/home/pi/.kodi/addons/plugin.video.vtm.go/resources/lib/vtmgo/vtmgostream.py", line 106, in get_stream
                                                subtitles = self._delay_subtitles(subtitles, json_manifest)
                                              File "/home/pi/.kodi/addons/plugin.video.vtm.go/resources/lib/vtmgo/vtmgostream.py", line 260, in _delay_subtitles
                                                if item.endswith('.vtt'):
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 35: ordinal not in range(128)
                                            -->End of Python script error report<--
2020-08-27 19:11:06.817 T:1900450736   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.vtm.go/play/catalog/channels/d8659669-b964-414c-aa9c-e31d8d15696b?.pvr]
2020-08-27 19:11:15.215 T:1900450736  NOTICE: Stopping player`

Think this is the log file you're looking for?

**Comment by michaelarnauts** [comment]
I think this is already fixed in the latest master branch. Can you try with https://github.com/add-ons/plugin.video.vtm.go/archive/master.zip ?

**Comment by michaelarnauts** [comment]
This might be fixed with #197

**Comment by billgoldbergmania** [comment]
> I think this is already fixed in the latest master branch. Can you try with https://github.com/add-ons/plugin.video.vtm.go/archive/master.zip ?

That seemed to work yes! Thanks a lot.

**Comment by michaelarnauts** [comment]
Allright, we will probably make a release in a few days when DPG changes the channels to VTM 2, VTM 3, ...
