### ISSUE TITLE
TV Guide doesn't work anymore

### ISSUE THREAD

**Issue by vermope** [add-ons/plugin.video.vtm.go#209]
**Describe the bug**
Service IPTV manager gives an error when fetching program schedule for all VTM GO channels. For the VTM GO channels there is no program data in the EPG.

**To Reproduce**
1. Go to VTM GO settings --> Integrations --> IPTV manager settings
2. Channels --> Refresh channels and guide now...
3. VTM GO won't load new program data

**Expected behavior**
New program schedule should fill the EPG automatically on a daily base

**Screenshots**

**System**
 - Addon version: VTM GO -> 1.1.2  / service.iptv.manager -> 0.1.0
 - Kodi version: 18.8
 - Inputstream adaptive version:
 - Operating System:  LibreElec 9.1.4
 - Special Hardware: X86/X64

**Comment by michaelarnauts** [comment]
> Service IPTV manager gives an error when fetching program schedule for all VTM GO channels. For the VTM GO channels there is no program data in the EPG.

Can you indicate what error you get and provide the relevant parts of your kodi.log? As far as I can tell, this should work fine.

**Comment by vermope** [comment]
@michaelarnauts I think this is the error:

2020-10-01 09:24:59.558 T:139979572193024   ERROR: [service.iptv.manager] [resources.lib.modules.addon] Something went wrong while calling plugin.video.vtm.go: Something went wrong in plugin.video.vtm.go
2020-10-01 09:24:59.567 T:139976714426112   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: No JSON object could be decoded
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.vtm.go/plugin.py", line 18, in <module>
                                                plugin.run(sys.argv)
                                              File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/plugin.py", line 218, in run
                                                routing.run(params)
                                              File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                self._dispatch(self.path)
                                              File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                view_func(**kwargs)
                                              File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/plugin.py", line 213, in iptv_epg
                                                IPTVManager(kodi, int(routing.args['port'][0])).send_epg()
                                              File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/modules/iptvmanager.py", line 38, in send
                                                sock.sendall(json.dumps(func(self)).encode())  # pylint: disable=not-callable
                                              File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/modules/iptvmanager.py", line 78, in send_epg
                                                channels = self._vtm_go_epg.get_epgs(date)
                                              File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/vtmgo/vtmgoepg.py", line 133, in get_epgs
                                                epg = json.loads(response)
                                              File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
                                              File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
                                              File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
                                            ValueError: No JSON object could be decoded
                                            -->End of Python script error report<--
2020-10-01 09:25:01.970 T:139977681794816  NOTICE: [plugin.video.vrt.nu] Access: plugin://plugin.video.vrt.nu/iptv/channels?port=39835
2020-10-01 09:25:01.973 T:139977681794816  NOTICE: [plugin.video.vrt.nu] Sending data output to IPTV Manager using port 39835
2020-10-01 09:25:02.302 T:139977681794816  NOTICE: [plugin.video.vrt.nu] Access: plugin://plugin.video.vrt.nu/iptv/epg?port=34631
2020-10-01 09:25:02.303 T:139977681794816  NOTICE: [plugin.video.vrt.nu] Sending data output to IPTV Manager using port 34631
2020-10-01 09:25:02.348 T:139977681794816  NOTICE: [plugin.video.vrt.nu] URL get: https://www.vrt.be/bin/epg/schedule.2020-09-30.json
2020-10-01 09:25:02.550 T:139977681794816  NOTICE: [plugin.video.vrt.nu] URL get: https://www.vrt.be/bin/epg/schedule.2020-10-01.json
2020-10-01 09:25:02.764 T:139977681794816  NOTICE: [plugin.video.vrt.nu] URL get: https://www.vrt.be/bin/epg/schedule.2020-10-02.json
2020-10-01 09:25:04.196 T:139979580585728  NOTICE: PVR Manager: Stopping
2020-10-01 09:25:04.299 T:139979580585728  NOTICE: PVR Manager: Stopped
2020-10-01 09:25:05.225 T:139976835032832  NOTICE: AddOnLog: PVR IPTV Simple Client: LoadPlayList PlayList Loaded - 0 (ms)
2020-10-01 09:25:05.225 T:139976835032832  NOTICE: AddOnLog: PVR IPTV Simple Client: Loaded 32 channels.
2020-10-01 09:25:05.225 T:139976835032832  NOTICE: PVR Manager: Starting
2020-10-01 09:25:05.229 T:139976819025664  NOTICE: PVR Manager: Started
2020-10-01 09:25:05.230 T:139979580585728  NOTICE: EPG thread started
2020-10-01 09:25:06.239 T:139977681794816  NOTICE: AddOnLog: PVR IPTV Simple Client: LoadEPG EPG Loaded - 9 (ms)
2020-10-01 09:30:01.372 T:139977132721920 WARNING: CAddonSettings[script.module.metahandler]: failed to parse old setting definition for "db_port" of type "integer"
2020-10-01 09:30:03.167 T:139977132721920   ERROR: [service.iptv.manager] [resources.lib.modules.addon] Something went wrong while calling plugin.video.vtm.go: Something went wrong in plugin.video.vtm.go
2020-10-01 09:30:03.174 T:139976858654464   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: No JSON object could be decoded
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.vtm.go/plugin.py", line 18, in <module>
                                                plugin.run(sys.argv)
                                              File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/plugin.py", line 218, in run
                                                routing.run(params)
                                              File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                self._dispatch(self.path)
                                              File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                view_func(**kwargs)
                                              File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/plugin.py", line 213, in iptv_epg
                                                IPTVManager(kodi, int(routing.args['port'][0])).send_epg()
                                              File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/modules/iptvmanager.py", line 38, in send
                                                sock.sendall(json.dumps(func(self)).encode())  # pylint: disable=not-callable
                                              File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/modules/iptvmanager.py", line 78, in send_epg
                                                channels = self._vtm_go_epg.get_epgs(date)
                                              File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/vtmgo/vtmgoepg.py", line 133, in get_epgs
                                                epg = json.loads(response)
                                              File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
                                              File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
                                              File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
                                            ValueError: No JSON object could be decoded

**Comment by michaelarnauts** [comment]
Krijg je ook een error als je vanuit de addon naar een kanaal gaat en daar de gids probeert te bekijken?

**Comment by vermope** [comment]
Jup, 

2020-10-01 16:05:07.931 T:139976714426112   ERROR: GetDirectory - Error getting plugin://plugin.video.vtm.go/tvguide/channel/vtm/today
2020-10-01 16:05:07.942 T:139979768330368   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vtm.go/tvguide/channel/vtm/today) failed
2020-10-01 16:05:13.343 T:139976669308672   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: No JSON object could be decoded
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.vtm.go/plugin.py", line 18, in <module>
                                                plugin.run(sys.argv)
                                              File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/plugin.py", line 218, in run
                                                routing.run(params)
                                              File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                self._dispatch(self.path)
                                              File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                view_func(**kwargs)
                                              File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/plugin.py", line 72, in show_tvguide_detail
                                                TvGuide(kodi).show_tvguide_detail(channel, date)
                                              File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/modules/tvguide.py", line 57, in show_tvguide_detail
                                                epg = self._vtm_go_epg.get_epg(channel=channel, date=date)
                                              File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/vtmgo/vtmgoepg.py", line 106, in get_epg
                                                epg = json.loads(response)
                                              File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
                                              File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
                                              File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
                                            ValueError: No JSON object could be decoded
                                            -->End of Python script error report<--
2020-10-01 16:05:13.745 T:139976358012672   ERROR: GetDirectory - Error getting plugin://plugin.video.vtm.go/tvguide/channel/vtm/tomorrow
2020-10-01 16:05:13.760 T:139979768330368   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vtm.go/tvguide/channel/vtm/tomorrow) failed

**Comment by michaelarnauts** [comment]
Hmm, ik heb het hier ook voor. Ik vermoed dat de API aangepast is bij VTM.

**Comment by dagwieers** [comment]
Ja, ik heb dat al een paar dagen. Ook al gemeld op Slack, maar ik dacht dat het misschien aan mijn master branch versie lag ofzo.

**Comment by canihavesomecoffee** [comment]
De URL (i.e. https://vtm.be/tv-gids/api/v2/broadcasts/2020-10-01) lijkt in elk geval vanuit de browser nog steeds te werken.

**Comment by canihavesomecoffee** [comment]
@dagwieers 

De user agent aanpassen naar een niet "bot-like" agent lijkt te werken bij mij:

```
import requests
s = requests.Session()
s.headers.update({'User-Agent': 'Firefox'})
s.get('https://vtm.be/tv-gids/api/v2/broadcasts/2020-10-01')
Out[5]: <Response [200]>
r = s.get('https://vtm.be/tv-gids/api/v2/broadcasts/2020-10-01')
r.text
Out[7]: '{"from":1601524800000,"to":1601611200000,"timestamp":1601578036899,"channels":[{"name":"VTM","seoKey":"vtm","uuid":"d8659669-b964-414c-aa9c-e31d8d15696b","channelLogoUrl":"https://images4.persgroep
```

**Comment by michaelarnauts** [comment]
Hmm, het leek te maken te hebben met de cookies. Met een clean session wordt je geredirect en moet je eerst accepteren. Dan krijg je een authId die je meegeeft met de cookies.

Vind het wel vreemd dat je useragent aanpassen ook werkt...

**Comment by canihavesomecoffee** [comment]
> Hmm, het leek te maken te hebben met de cookies. Met een clean session wordt je geredirect en moet je eerst accepteren. Dan krijg je een authId die je meegeeft met de cookies.
> 
> Vind het wel vreemd dat je useragent aanpassen ook werkt...

Ik ga nog eens proberen met een totaal andere user agent dan mijn gebruikelijke browser (waar een sessie actief is), maar het lijkt er wel op dat het een soort detectie van bots/scrapers is...

**Comment by canihavesomecoffee** [comment]
```
import requests
s = requests.Session()
r = s.get('https://vtm.be/tv-gids/api/v2/broadcasts/2020-10-01')
r.text[:10]
Out[5]: '<!DOCTYPE '
r = s.get('https://vtm.be/privacygate-confirm?redirectUri=%2Ftv-gids%2Fapi%2Fv2%2Fbroadcasts%2F2020-10-01')
r.text[:10]
Out[7]: '{"from":16'
```

Dit lijkt vrij fool-proof te werken.

**Comment by mediaminister** [comment]
Thanks @canihavesomecoffee I made a pull request based on your solution.

**Comment by frankdpGH** [comment]
Thanks for the quick fix!!!
