### ISSUE TITLE
VTM Go error at kodi startup when refreshing kodi video library

### ISSUE THREAD

**Issue by badoneti** [add-ons/plugin.video.vtm.go#260]
**Describe the bug**
When starting Kodi, VTMGo addon is displaying an error

**To Reproduce**
1. Start Kodi on LibreElec
2. Refresh kodi video library (automatic)

**Expected behavior**
No error, at most a warning if a program is no longer available

**System**
```
Kodi (18.9 (18.9.0) Git:18.9-Leia). 
Running on LibreELEC (official): 9.2.6, 
Linux x86 64-bit version 5.1.16
FFmpeg version/source: 4.0.4-Kodi
Intel(R) Atom(TM) CPU Z3735F
Plugin v1.2.2
```
**Additional context**
```
2021-02-03 22:09:48.956 T:140262705489664   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'resources.lib.vtmgo.exceptions.UnavailableException'>
                                            Error Contents: 404 Client Error: Not Found for url: https://lfvp-api.dpgmedia.net/vtmgo/programs/e17be408-82f0-4bca-b14f-59e21a1b0d6a
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.vtm.go/addon_entry.py", line 18, in <module>
                                                run(argv)
                                              File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/addon.py", line 318, in run
                                                routing.run(params)
                                              File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                self._dispatch(self.path)
                                              File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                view_func(**kwargs)
                                              File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/addon.py", line 185, in library_tvshows
                                                Library().show_library_tvshows_program(program)
                                              File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/modules/library.py", line 82, in show_library_tvshows_program
                                                program_obj = self._api.get_program(program)
                                              File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/vtmgo/vtmgo.py", line 294, in get_program
                                                profile=self._tokens.profile)
                                              File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/vtmgo/util.py", line 45, in http_get
                                                raise UnavailableException(exc)
                                            UnavailableException: 404 Client Error: Not Found for url: https://lfvp-api.dpgmedia.net/vtmgo/programs/e17be408-82f0-4bca-b14f-59e21a1b0d6a
                                            -->End of Python script error report<--
2021-02-03 22:09:49.060 T:140264496686848   ERROR: GetDirectory - Error getting plugin://plugin.video.vtm.go/library/tvshows/?program=e17be408-82f0-4bca-b14f-59e21a1b0d6a
```

**Comment by michaelarnauts** [comment]
Do you still see this issue at startup with the latest version of the addon?

**Comment by badoneti** [comment]
Hard to say, I upgraded to libreelec 10 & kodi matrix where this is problem does not appear.

**Comment by michaelarnauts** [comment]
Okay, I'll consider this fixed then :) Thanks for the reply!
