### ISSUE TITLE
HTTP 426 Error

### ISSUE THREAD

**Issue by pthyseba** [add-ons/plugin.video.vtm.go#275]
**Describe the bug**
Watching Live TV ("Channels") using VTM Go no longer works

**To Reproduce**
Open VTM Go addon
Select "Channels"

Output (kodi.log):
2021-05-03 17:35:05.765 T:2238829424  NOTICE: [plugin.video.vtm.go] [resources.lib.service] Service started
2021-05-03 17:35:05.773 T:2238829424  NOTICE: [plugin.video.vtm.go] [resources.lib.service] Starting Manifest Proxy...
2021-05-03 17:35:05.973 T:2696303472  NOTICE: [plugin.video.vtm.go] [resources.lib.modules.proxy] Listening on port 58173
2021-05-03 17:35:06.024 T:2238829424  NOTICE: [plugin.video.vtm.go] [resources.lib.vtmgo.vtmgoauth] JWT is valid
2021-05-03 17:35:06.024 T:2238829424  NOTICE: [plugin.video.vtm.go] [resources.lib.vtmgo.util] Sending GET https://lfvp-api.dpgmedia.net/vtmgo/catalog
2021-05-03 17:35:06.034 T:2238829424  NOTICE: [plugin.video.vtm.go] [urllib3.connectionpool] Starting new HTTPS connection (1): lfvp-api.dpgmedia.net:443
2021-05-03 17:35:06.278 T:2238829424  NOTICE: [plugin.video.vtm.go] [urllib3.connectionpool] https://lfvp-api.dpgmedia.net:443 "GET /vtmgo/catalog?pageSize=2000 HTTP/1.1" 426 0
2021-05-03 17:35:06.280 T:2238829424  NOTICE: [plugin.video.vtm.go] [resources.lib.vtmgo.util] Got response (status=426):
2021-05-03 17:35:06.283 T:2238829424   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'requests.exceptions.HTTPError'>
                                            Error Contents: 426 Client Error: Unknown for url: https://lfvp-api.dpgmedia.net/vtmgo/catalog?pageSize=2000
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.vtm.go/service_entry.py", line 17, in <module>
                                                run()
                                              File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/service.py", line 191, in run
                                                BackgroundService().run()
                                              File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/service.py", line 40, in run
                                                self._update_metadata()
                                              File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/service.py", line 65, in _update_metadata
                                                success = Metadata().fetch_metadata(callback=update_status)
                                              File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/modules/metadata.py", line 52, in fetch_metadata
                                                items = self._vtm_go.get_items()
                                              File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/vtmgo/vtmgo.py", line 224, in get_items
                                                profile=self._tokens.profile if self._tokens else None)
                                              File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/vtmgo/util.py", line 42, in http_get
                                                return _request('GET', url=url, params=params, token=token, profile=profile, headers=headers)
                                              File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/vtmgo/util.py", line 177, in _request
                                                response.raise_for_status()
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/models.py", line 940, in raise_for_status
                                                raise HTTPError(http_error_msg, response=self)
                                            HTTPError: 426 Client Error: Unknown for url: https://lfvp-api.dpgmedia.net/vtmgo/catalog?pageSize=2000
                                            -->End of Python script error report<--

**Expected behavior**
Channel list shows

**System**
 - vtmgo 1.2.5
 - Kodi version: (18.9.0) Git:leia_pi4_18.9-Leia
 - inputstream.adaptive v2.4.7.1
 - LibreElec 9.2.6 / RPi4

**Comment by kengithub9** [comment]
I have the same problem in kodi19.  On the channels and tvsimple addon.
Kodi version: 19.0
inputstream adaptive v2.6.13.1
CoreElec 19.1 rc4 - Beelink GT-King

**Comment by mediaminister** [comment]
I fixed this in https://github.com/add-ons/plugin.video.vtm.go/pull/276, but you should remove` auth-tokens.json` file manually from .kodi/userdata/addon_data/plugin.video.vtm.go/tokens to make it work.

**Comment by FilipDem** [comment]
Hi, I have the same issue... However I suppose this is the same for all (Belgian) users.
Will a new release be issued for an automatic update? Or should we update manually? 
Thanks for the information.
Filip

**Comment by cometoluc** [comment]
Sorry but i am a beginner. If i open vtmgo addon there it stays doing nothing. Just rolling the wheel below right
