### ISSUE TITLE
Impossible to play s11e0 boer zkt vrouw

### ISSUE THREAD

**Issue by badoneti** [add-ons/plugin.video.vtm.go#288]
**Describe the bug**
Error trying to play the episode

**To Reproduce**
1. Open VTMgo on kodi
2. Load s11e0 of boer zkt vrouw
3. error

**Expected behavior**
no error

**System**
 - Addon version: 1.2.7 matrix
 - Kodi version: 19.1
 - Inputstream adaptive version: 2.6.16.1
 - Operating System: LibreElec 10b4
 - Special Hardware: intel

**Additional context**
`021-06-01 19:04:36.758 T:819      INFO <general>: CActiveAESink::OpenSink - initialize sink
2021-06-01 19:04:36.758 T:819      INFO <general>: CAESinkALSA::Initialize - Attempting to open device "default"
2021-06-01 19:04:36.767 T:819      INFO <general>: CAESinkALSA::Initialize - Opened device "default"
2021-06-01 19:04:36.768 T:819      INFO <general>: CAESinkALSA::InitializeHW - Your hardware does not support AE_FMT_FLOAT, trying other formats
2021-06-01 19:04:36.769 T:819      INFO <general>: CAESinkALSA::InitializeHW - Using data format AE_FMT_S24NE4
2021-06-01 19:04:37.166 T:947   WARNING <general>: [script.module.inputstreamhelper] Widevine update check was made on 2021-05-27 20:38
2021-06-01 19:04:38.922 T:947     ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: unsupported operand type(s) for +: 'NoneType' and 'int'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.vtm.go/addon_entry.py", line 18, in <module>
                                                       run(argv)
                                                     File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/addon.py", line 325, in run
                                                       routing.run(params)
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/addon.py", line 305, in play
                                                       Player().play(category, item)
                                                     File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/modules/player.py", line 123, in play
                                                       next_episode_details = self._vtm_go.get_next_episode_from_program(program, episode_details.season, episode_details.number)
                                                     File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/vtmgo/vtmgo.py", line 379, in get_next_episode_from_program
                                                       if episode.season == season and episode.number == number + 1:
                                                   TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
                                                   -->End of Python script error report<--
                                                   
2021-06-01 19:04:39.342 T:947      INFO <general>: Python interpreter stopped
2021-06-01 19:04:39.356 T:813      INFO <general>: Skipped 4 duplicate messages..
2021-06-01 19:04:39.356 T:813     ERROR <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.vtm.go/play/catalog/episodes/016d389c-fb18-49cf-ae33-778a89f9acf5]
2021-06-01 19:04:39.386 T:813      INFO <general>: CVideoPlayer::CloseFile()
2021-06-01 19:04:39.387 T:888      INFO <general>: CVideoPlayer::OnExit()
2021-06-01 19:04:39.387 T:888      INFO <general>: Closing stream player 1
2021-06-01 19:04:39.388 T:888      INFO <general>: Waiting for audio thread to exit
2021-06-01 19:04:39.394 T:813      INFO <general>: VideoPlayer: waiting for threads to exit
2021-06-01 19:04:39.422 T:894      INFO <general>: thread end: CVideoPlayerAudio::OnExit()
2021-06-01 19:04:39.423 T:888      INFO <general>: Closing audio device
2021-06-01 19:04:39.475 T:819      INFO <general>: CActiveAESink::OpenSink - initialize sink
2021-06-01 19:04:39.475 T:888      INFO <general>: Deleting audio codec
2021-06-01 19:04:39.475 T:888      INFO <general>: Closing stream player 2
2021-06-01 19:04:39.477 T:888      INFO <general>: waiting for video thread to exit
2021-06-01 19:04:39.479 T:892   WARNING <general>: OutputPicture - timeout waiting for buffer
2021-06-01 19:04:39.479 T:892      INFO <general>: thread end: video_thread
2021-06-01 19:04:39.482 T:888      INFO <general>: deleting video codec
2021-06-01 19:04:39.485 T:888      INFO <general>: VAAPI::Close
2021-06-01 19:04:39.486 T:904      INFO <general>: COutput::OnExit: Output Thread terminated
2021-06-01 19:04:39.486 T:888      INFO <general>: VAAPI::Close - closing decoder context
2021-06-01 19:04:39.498 T:888      INFO <general>: ADDON: Dll Destroyed - InputStream Adaptive
2021-06-01 19:04:39.499 T:813      INFO <general>: VideoPlayer: finished waiting
2021-06-01 19:04:39.499 T:813      INFO <general>: CVideoPlayer::CloseFile()
2021-06-01 19:04:39.499 T:813      INFO <general>: VideoPlayer: waiting for threads to exit
2021-06-01 19:04:39.499 T:813      INFO <general>: VideoPlayer: finished waiting

`

**Comment by mediaminister** [comment]
I checked and episode has a `None` value, setting this to zero fixes this problem.
