### ISSUE TITLE
Cannot use version of the kodi repository

### ISSUE THREAD

**Issue by GikikCrowchew** [add-ons/plugin.video.vtm.go#315]
**Describe the bug**

**To Reproduce**
1. Install addon
2. Configure login
3. Launch addon

**Expected behavior**

**Screenshots**

**Logs**
Add debug logs to help troubleshoot the issue. See https://kodi.wiki/view/Log_file/Easy for more info.

**System**
 - Addon version: 1.2.12+matrix.1
 - Kodi version: 19.3.0
 - Inputstream adaptive version:
 - Operating System (Windows / Mac OS / Android / LibreElec / OSMC / ...):
 - Special Hardware (RPI / Vero4K+ / ...):

**Additional context**

2022-02-02 11:09:56.983 T:11032   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'resources.lib.vtmgo.exceptions.InvalidLoginException'>
                                                   Traceback (most recent call last):
                                                     File "C:\Users\\AppData\Roaming\Kodi\addons\plugin.video.vtm.go\resources\lib\vtmgo\vtmgoauth.py", line 211, in _android_login
                                                       response = util.http_post('https://login2.vtm.be/login',
                                                     File "C:\Users\\AppData\Roaming\Kodi\addons\plugin.video.vtm.go\resources\lib\vtmgo\util.py", line 70, in http_post
                                                       return _request('POST', url=url, params=params, form=form, data=data, token=token, profile=profile, headers=headers)
                                                     File "C:\Users\\AppData\Roaming\Kodi\addons\plugin.video.vtm.go\resources\lib\vtmgo\util.py", line 177, in _request
                                                       response.raise_for_status()
                                                     File "C:\Users\\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\models.py", line 943, in raise_for_status
                                                       raise HTTPError(http_error_msg, response=self)
                                                   requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://login2.vtm.be/login?client_id=vtm-go-android
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "C:\Users\\AppData\Roaming\Kodi\addons\plugin.video.vtm.go\addon_entry.py", line 18, in <module>
                                                       run(argv)
                                                     File "C:\Users\\AppData\Roaming\Kodi\addons\plugin.video.vtm.go\resources\lib\addon.py", line 325, in run
                                                       routing.run(params)
                                                     File "C:\Users\\AppData\Roaming\Kodi\addons\script.module.routing\lib\routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "C:\Users\\AppData\Roaming\Kodi\addons\script.module.routing\lib\routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "C:\Users\\AppData\Roaming\Kodi\addons\plugin.video.vtm.go\resources\lib\addon.py", line 76, in auth_clear_tokens
                                                       Authentication().clear_tokens()
                                                     File "C:\Users\\AppData\Roaming\Kodi\addons\plugin.video.vtm.go\resources\lib\modules\authentication.py", line 21, in __init__
                                                       self._auth = VtmGoAuth(kodiutils.get_setting('username'),
                                                     File "C:\Users\\AppData\Roaming\Kodi\addons\plugin.video.vtm.go\resources\lib\vtmgo\vtmgoauth.py", line 103, in __init__
                                                       self.login()
                                                     File "C:\Users\\AppData\Roaming\Kodi\addons\plugin.video.vtm.go\resources\lib\vtmgo\vtmgoauth.py", line 173, in login
                                                       self._android_login()
                                                     File "C:\Users\\AppData\Roaming\Kodi\addons\plugin.video.vtm.go\resources\lib\vtmgo\vtmgoauth.py", line 221, in _android_login
                                                       raise InvalidLoginException()
                                                   resources.lib.vtmgo.exceptions.InvalidLoginException
                                                   -->End of Python script error report<--
                                                   
2022-02-02 11:09:57.078 T:11032    INFO <general>: Python interpreter stopped
2022-02-02 11:10:01.400 T:912   WARNING <general>: CGUIWindowManager - CGUIWindowManager::HandleAction - ignoring action 107, because topmost modal dialog closing animation is running
2022-02-02 11:10:01.575 T:11980   ERROR <general>: Skipped 4 duplicate messages..
2022-02-02 11:10:01.575 T:11980   ERROR <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.vtm.go/
2022-02-02 11:10:01.575 T:13772    INFO <general>: CPythonInvoker(8, C:\Users\\AppData\Roaming\Kodi\addons\plugin.video.vtm.go\addon_entry.py): script successfully run
2022-02-02 11:10:01.601 T:912     ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vtm.go/) failed
2022-02-02 11:10:01.657 T:13772    INFO <general>: Python interpreter stopped
2022-02-02 11:10:08.767 T:912      INFO <general>: Loading skin file: Settings.xml, load type: KEEP_IN_MEMORY
2022-02-02 11:10:10.400 T:912      INFO <general>: Loading skin file: EventLog.xml, load type: KEEP_IN_MEMORY

**Comment by michaelarnauts** [comment]
Hmm, that's odd, `1.2.12+matrix.1` is known to be broken, but the Kodi repository should contain the latest 1.3.0 version. Do you have an odd non-standard Kodi build with own repositories or something?

I can see here https://kodi.tv/addons/matrix/plugin.video.vtm.go that Kodi has the 1.3.0+matrix.1 version.

**Comment by GikikCrowchew** [comment]
> Hmm, that's odd, `1.2.12+matrix.1` is known to be broken, but the Kodi repository should contain the latest 1.3.0 version. Do you have an odd non-standard Kodi build with own repositories or something?
> 
> I can see here https://kodi.tv/addons/matrix/plugin.video.vtm.go that Kodi has the 1.3.0+matrix.1 version.

Indeed, I can see that you are corret and it is on de kodi.tv website, but I am talking about what gets installed when you go into kodi and install addon from repository.
Perhaps it is linked to older windows version or something, I don't know, but you an repoduce it, it didn't install this version, but an older version

**Comment by michaelarnauts** [comment]
We've checked this on a variety of Windows systems (32bit and 64bit), but couldn't reproduce this. We always got the latest release.

Can you tell more about your setup? Are you using a proxy server or something? What do you get when you let Kodi search for updates? Also, what is the version of the TV Vlaanderen add-on for example? This has been updated recently also.

**Comment by michaelarnauts** [comment]
Closing due to inactivity and unable to reproduce.
