### ISSUE TITLE
Kodi 18.9 (Leia), LibreElec 9.2.8 - Can't play stream

### ISSUE THREAD

**Issue by PeterCloet** [add-ons/plugin.video.vtm.go#322]
Describe the bug
Cannot play streams on VTMGo.

System
    Addon version: 1.3.0 (2021-12-19)
    Kodi version: 18.9 (LibreElec 9.2.8)
    Inputstream adaptive version: 2.4.8.1
    Operating System: Libreelec
    Special Hardware (RPI / Vero4K+ / ...): RPI 4

Additional context

2022-03-29 08:39:16.684 T:3011428992   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
2022-03-29 08:39:17.302 T:2335167296  NOTICE: [plugin.video.vtm.go] [resources.lib.vtmgo.vtmgoauth] JWT is valid
2022-03-29 08:39:18.572 T:2335167296  NOTICE: Previous line repeats 2 times.
2022-03-29 08:39:18.572 T:2335167296  NOTICE: [plugin.video.vtm.go] [resources.lib.vtmgo.util] Sending GET https://lfvp-api.dpgmedia.net/vtmgo/storefronts/1c683de4-3fb0-4cc4-9d9c-c365eba1b155
2022-03-29 08:39:18.582 T:2335167296  NOTICE: Previous line repeats 1 times.
2022-03-29 08:39:18.582 T:2335167296  NOTICE: [plugin.video.vtm.go] [urllib3.connectionpool] Starting new HTTPS connection (1): lfvp-api.dpgmedia.net:443
2022-03-29 08:39:18.893 T:2335167296  NOTICE: Previous line repeats 1 times.
2022-03-29 08:39:18.893 T:2335167296  NOTICE: [plugin.video.vtm.go] [urllib3.connectionpool] https://lfvp-api.dpgmedia.net:443 "GET /vtmgo/storefronts/1c683de4-3fb0-4cc4-9d9c-c365eba1b155 HTTP/1.1" 200 None
2022-03-29 08:39:18.973 T:2335167296  NOTICE: Previous line repeats 1 times.
2022-03-29 08:39:18.973 T:2335167296  NOTICE: [plugin.video.vtm.go] [resources.lib.vtmgo.util] Got response (status=200): {"hashedAccountId":"81981a1c2f9333717909dca821329df0","profiles":[{"id":"01416954-ff4f-4da6-8d1f-f5fc27e04720","name":"Peter Cloet","color":{"id":1001,"start":"#64d8e3","end":"#094aa9"},"product":"VTM_GO"}],"abroad":false,"rows":[{"id":"b010d567-facc-462c-8a4d-b7a925f31861","rowType":"TOP_BANNER","teaser":{"tagline":"","bannerAltText":"","largeImageUrl":"https://images2.persgroep.net/rcs/qth7yQ3FwbHpLAsoxVB2fnquMQw/diocontent/212394722/_fitwidth/2400?appId=038a353bad43ac27fd436dc5419c256b&quality=0.9","mediumImageUrl":"https://images4.persgroep.net/rcs/LTUo1lJmHMRM7YDSzs4LTH92Ph4/diocontent/212394720/_fitwidth/1440?appId=038a353bad43ac27fd436dc5419c256b&quality=0.9","mobileImageUrl":"https://images3.persgroep.net/rcs/XwCrsBsMtGMrYpA8KQB6HHghWgI/diocontent/212394721/_fitwidth/1536?appId=038a353bad43ac27fd436dc5419c256b&quality=0.9","mobileCompressedImageUrl":"https://images1.persgroep.net/rcs/B3xJ1ChjmkK3VFE2mT4bX1OCn6k/diocontent/212394721/_fitwidth/768?appId=038a353bad43ac27fd436dc5419c256b&quality=0.9","sma
2022-03-29 08:39:18.993 T:2335167296  NOTICE: Previous line repeats 1 times.
2022-03-29 08:39:18.993 T:2335167296  NOTICE: [plugin.video.vtm.go] [resources.lib.kodiutils] Fetching /storage/.kodi/userdata/addon_data/plugin.video.vtm.go/cache/program.8ef77e41-0ed2-4ccd-9543-36bef17af30c from cache
2022-03-29 08:39:18.996 T:2335167296  NOTICE: Previous line repeats 1 times.
2022-03-29 08:39:18.996 T:2335167296  NOTICE: [plugin.video.vtm.go] [resources.lib.vtmgo.vtmgo] Skipping recommendation Kijk Verder with type CONTINUE_WATCHING
2022-03-29 08:39:18.996 T:2335167296  NOTICE: Previous line repeats 1 times.
2022-03-29 08:39:18.996 T:2335167296  NOTICE: [plugin.video.vtm.go] [resources.lib.vtmgo.vtmgo] Skipping recommendation None with type BANNER
2022-03-29 08:39:20.315 T:2335167296  NOTICE: Previous line repeats 1 times.
2022-03-29 08:39:20.315 T:2335167296  NOTICE: [plugin.video.vtm.go] [resources.lib.vtmgo.vtmgoauth] JWT is valid
2022-03-29 08:39:20.320 T:2335167296  NOTICE: Previous line repeats 2 times.
2022-03-29 08:39:20.320 T:2335167296  NOTICE: [plugin.video.vtm.go] [resources.lib.vtmgo.util] Sending GET https://lfvp-api.dpgmedia.net/vtmgo/programs/8ef77e41-0ed2-4ccd-9543-36bef17af30c
2022-03-29 08:39:20.478 T:2335167296  NOTICE: Previous line repeats 2 times.
2022-03-29 08:39:20.478 T:2335167296  NOTICE: [plugin.video.vtm.go] [urllib3.connectionpool] https://lfvp-api.dpgmedia.net:443 "GET /vtmgo/programs/8ef77e41-0ed2-4ccd-9543-36bef17af30c HTTP/1.1" 200 16272
2022-03-29 08:39:20.482 T:2335167296  NOTICE: Previous line repeats 2 times.
2022-03-29 08:39:20.482 T:2335167296  NOTICE: [plugin.video.vtm.go] [resources.lib.vtmgo.util] Got response (status=200): {"hashedAccountId":"81981a1c2f9333717909dca821329df0","profiles":[{"id":"01416954-ff4f-4da6-8d1f-f5fc27e04720","name":"Peter Cloet","color":{"id":1001,"start":"#64d8e3","end":"#094aa9"},"product":"VTM_GO"}],"abroad":false,"program":{"id":"8ef77e41-0ed2-4ccd-9543-36bef17af30c","name":"De Verraders","description":"Staf Coppens neemt achttien bekende Vlamingen mee naar een mysterieus kasteel voor een psychologisch spel vol leugens, verraad, manipulatie en verdachtmakingen.","bigPhotoUrl":"https://images1.persgroep.net/rcs/gS6h4-blezdPVSNbqXScF1PIGQY/diocontent/211973991/_fitwidth/1400?appId=038a353bad43ac27fd436dc5419c256b&quality=0.8","mediumPhotoUrl":"https://images2.persgroep.net/rcs/wQyoS_TQ--iLaN7u7-CkSrIDM78/diocontent/211973991/_fitwidth/1280?appId=038a353bad43ac27fd436dc5419c256b&quality=0.8","smallPhotoUrl":"https://images1.persgroep.net/rcs/vNljUlLU09QvsfTTDOWuKfKdPh0/diocontent/211973991/_fitwidth/426?appId=038a353bad43ac27fd436dc5419c256b&quality=0.8","teaserImageUrl":"https://images4.persgroep.net/r
2022-03-29 08:39:20.485 T:2335167296  NOTICE: Previous line repeats 2 times.
2022-03-29 08:39:20.485 T:2335167296  NOTICE: [plugin.video.vtm.go] [resources.lib.kodiutils] Storing to cache as /storage/.kodi/userdata/addon_data/plugin.video.vtm.go/cache/program.8ef77e41-0ed2-4ccd-9543-36bef17af30c
2022-03-29 08:39:20.523 T:2335167296  NOTICE: Previous line repeats 2 times.
2022-03-29 08:39:20.523 T:2335167296  NOTICE: [plugin.video.vtm.go] [resources.lib.kodiutils] Fetching /storage/.kodi/userdata/addon_data/plugin.video.vtm.go/cache/program.8ef77e41-0ed2-4ccd-9543-36bef17af30c from cache
2022-03-29 08:39:21.579 T:2335167296  NOTICE: Previous line repeats 2 times.
2022-03-29 08:39:21.579 T:2335167296  NOTICE: [plugin.video.vtm.go] [resources.lib.vtmgo.vtmgoauth] JWT is valid
2022-03-29 08:39:22.235 T:2335167296  NOTICE: Previous line repeats 7 times.
2022-03-29 08:39:22.235 T:2335167296   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'ascii' codec can't decode byte 0xe2 in position 58437: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.vtm.go/addon_entry.py", line 18, in <module>
                                                run(argv)
                                              File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/addon.py", line 179, in run
                                                routing.run(params)
                                              File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                self._dispatch(self.path)
                                              File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                view_func(**kwargs)
                                              File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/addon.py", line 159, in play
                                                Player().play(category, item)
                                              File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/modules/player.py", line 50, in play
                                                if not self._check_inputstream():
                                              File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/modules/player.py", line 178, in _check_inputstream
                                                if not is_helper.check_inputstream():
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 407, in check_inputstream
                                                return self._check_drm()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 359, in _check_drm
                                                return self._check_widevine()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 329, in _check_widevine
                                                self._update_widevine()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 288, in _update_widevine
                                                latest_version = latest_widevine_version()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/widevine.py", line 164, in latest_widevine_version
                                                devices = chromeos_config()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm.py", line 63, in chromeos_config
                                                return json.loads(http_get(config.CHROMEOS_RECOVERY_URL))
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/utils.py", line 73, in http_get
                                                return content.decode()
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 58437: ordinal not in range(128)
                                            -->End of Python script error report<--
2022-03-29 08:39:22.437 T:3011428992   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.vtm.go/play/catalog/episodes/7d75391e-295a-4b95-893b-3c7a0603b5d7]

**Comment by michaelarnauts** [comment]
You'll need to update Inputstream helper.

**Comment by PeterCloet** [comment]
Thank you for the feedback.
Seems like Libreelec 9.2.8 only supports up to v2.4.8.1.
I will look into upgrading to Libreelec 10 to get hold of a more recent version.

**Comment by PeterCloet** [comment]
I upgraded to Libreelec 10.0.2 (Matrix).
This version contains a more recent version of InputStream Adaptive.
VTM Go now works flawlesly.
Thanks for your help!
