### ISSUE TITLE
Unable to install the addon.

### ISSUE THREAD

**Issue by Jefken** [add-ons/plugin.video.vtm.go#339]
Hi,

Seems that I'm unable to install or to start the addon without an error popup, Someone is wanting me to help?
Tnanks and regards.

2022-11-13 10:18:25.270 T:3784     INFO <general>: CAddonMgr::FindAddon: plugin.video.vtm.go v1.3.2+matrix.1 installed
2022-11-13 10:18:25.379 T:3870     INFO <general>: initializing python engine.
2022-11-13 10:18:25.731 T:3631  WARNING <general>: CGUIMediaWindow::OnMessage - updating in progress
2022-11-13 10:18:26.563 T:3870    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ModuleNotFoundError'>
                                                   Error Contents: No module named 'requests.__version__'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.vtm.go/service_entry.py", line 15, in <module>
                                                       from resources.lib.service import run
                                                     File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/service.py", line 11, in <module>
                                                       from resources.lib.modules.proxy import Proxy
                                                     File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/modules/proxy.py", line 16, in <module>
                                                       import requests
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/__init__.py", line 129, in <module>
                                                       from .__version__ import __title__, __description__, __url__, __version__
                                                   ModuleNotFoundError: No module named 'requests.__version__'
                                                   -->End of Python script error report<--
                                                   
2022-11-13 10:18:26.977 T:3870     INFO <general>: Python interpreter stopped

**System**
 - plugin.video.vtm.go-1.3.2+matrix.1.zip
 - Kodi version: Matrix
 - Inputstream adaptive version:
 - CoreElec 19.5 Matrix rc2
 - Amlogic S905X3

**Comment by michaelarnauts** [comment]
It looks like you are missing some dependencies. Did you install from the Kodi repository? (So without downloading a zip file manually). If you go to the add-on information screen, you have an option to install dependencies there.

It might help to restart afterwards.
