### ISSUE TITLE
App does not start

### ISSUE THREAD

**Issue by Proj3ctS** [add-ons/plugin.video.vtm.go#370]
**Describe the bug**
It is not possible to open the app. It seems that the change to the new version of the API has changed the token URL

**To Reproduce**
1. Start the app
2. Check the log

**Expected behavior**
The app is started
Clearing the cache and tokens did not fix the issue

**Screenshots**
N/A

**Logs**
2023-11-05 22:38:05.775 T:1138     info <general>: [plugin.video.vtm.go] [resources.lib.vtmgo.util] Sending POST https://login2.vtm.be/device/authorize: {'client_id': 'vtm-go-androidtv'}
2023-11-05 22:38:05.781 T:1138     info <general>: [plugin.video.vtm.go] [urllib3.connectionpool] Starting new HTTPS connection (1): login2.vtm.be:443
2023-11-05 22:38:06.020 T:1138     info <general>: [plugin.video.vtm.go] [urllib3.connectionpool] https://login2.vtm.be:443 "POST /device/authorize HTTP/1.1" 200 244
2023-11-05 22:38:06.022 T:1138     info <general>: [plugin.video.vtm.go] [resources.lib.vtmgo.util] Got response (status=200): {"user_code":"BQTVTH","device_code":"avuCgrEy0iu2VtqYqgCKqvuZcD-QoM1NDFRzVmw--v8","interval":2,"verification_uri_complete":"https://login2.vtm.be/androidtv?user_code=BQTVTH","verification_uri":"https://login2.vtm.be/androidtv","expires_in":300}
2023-11-05 22:38:06.034 T:1025     info <general>: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY
2023-11-05 22:38:06.036 T:1138     info <general>: [plugin.video.vtm.go] [resources.lib.vtmgo.util] Sending POST https://login2.vtm.be/token: {'device_code': 'avuCgrEy0iu2VtqYqgCKqvuZcD-QoM1NDFRzVmw--v8', 'client_id': 'vtm-go-androidtv', 'grant_type': 'urn:ietf:params:oauth:grant-type:device_code'}
2023-11-05 22:38:06.146 T:1138     info <general>: [plugin.video.vtm.go] [urllib3.connectionpool] https://login2.vtm.be:443 "POST /token HTTP/1.1" 400 127
2023-11-05 22:38:06.148 T:1138     info <general>: [plugin.video.vtm.go] [resources.lib.vtmgo.util] Got response (status=400): {"error_description":"[A242307] The device authorization request has not been authorized yet.","error":"authorization_pending"}
2023-11-05 22:38:08.149 T:1138     info <general>: [plugin.video.vtm.go] [resources.lib.vtmgo.util] Sending POST https://login2.vtm.be/token: {'device_code': 'avuCgrEy0iu2VtqYqgCKqvuZcD-QoM1NDFRzVmw--v8', 'client_id': 'vtm-go-androidtv', 'grant_type': 'urn:ietf:params:oauth:grant-type:device_code'}
2023-11-05 22:38:08.152 T:1138     info <general>: [plugin.video.vtm.go] [urllib3.connectionpool] Resetting dropped connection: login2.vtm.be
2023-11-05 22:38:08.398 T:1138     info <general>: [plugin.video.vtm.go] [urllib3.connectionpool] https://login2.vtm.be:443 "POST /token HTTP/1.1" 400 127
2023-11-05 22:38:08.399 T:1138     info <general>: [plugin.video.vtm.go] [resources.lib.vtmgo.util] Got response (status=400): {"error_description":"[A242307] The device authorization request has not been authorized yet.","error":"authorization_pending"}
2023-11-05 22:38:10.400 T:1138     info <general>: [plugin.video.vtm.go] [resources.lib.vtmgo.util] Sending POST https://login2.vtm.be/token: {'device_code': 'avuCgrEy0iu2VtqYqgCKqvuZcD-QoM1NDFRzVmw--v8', 'client_id': 'vtm-go-androidtv', 'grant_type': 'urn:ietf:params:oauth:grant-type:device_code'}
2023-11-05 22:38:10.406 T:1138     info <general>: [plugin.video.vtm.go] [urllib3.connectionpool] Resetting dropped connection: login2.vtm.be
2023-11-05 22:38:10.682 T:1138     info <general>: [plugin.video.vtm.go] [urllib3.connectionpool] https://login2.vtm.be:443 "POST /token HTTP/1.1" 400 127
2023-11-05 22:38:10.683 T:1138     info <general>: [plugin.video.vtm.go] [resources.lib.vtmgo.util] Got response (status=400): {"error_description":"[A242307] The device authorization request has not been authorized yet.","error":"authorization_pending"}
2023-11-05 22:38:12.684 T:1138     info <general>: [plugin.video.vtm.go] [resources.lib.vtmgo.util] Sending POST https://login2.vtm.be/token: {'device_code': 'avuCgrEy0iu2VtqYqgCKqvuZcD-QoM1NDFRzVmw--v8', 'client_id': 'vtm-go-androidtv', 'grant_type': 'urn:ietf:params:oauth:grant-type:device_code'}
2023-11-05 22:38:12.687 T:1138     info <general>: [plugin.video.vtm.go] [urllib3.connectionpool] Resetting dropped connection: login2.vtm.be
2023-11-05 22:38:12.937 T:1138     info <general>: [plugin.video.vtm.go] [urllib3.connectionpool] https://login2.vtm.be:443 "POST /token HTTP/1.1" 400 127
2023-11-05 22:38:12.938 T:1138     info <general>: [plugin.video.vtm.go] [resources.lib.vtmgo.util] Got response (status=400): {"error_description":"[A242307] The device authorization request has not been authorized yet.","error":"authorization_pending"}
2023-11-05 22:38:14.939 T:1138     info <general>: [plugin.video.vtm.go] [resources.lib.vtmgo.util] Sending POST https://login2.vtm.be/token: {'device_code': 'avuCgrEy0iu2VtqYqgCKqvuZcD-QoM1NDFRzVmw--v8', 'client_id': 'vtm-go-androidtv', 'grant_type': 'urn:ietf:params:oauth:grant-type:device_code'}
2023-11-05 22:38:14.942 T:1138     info <general>: [plugin.video.vtm.go] [urllib3.connectionpool] Resetting dropped connection: login2.vtm.be
2023-11-05 22:38:15.191 T:1138     info <general>: [plugin.video.vtm.go] [urllib3.connectionpool] https://login2.vtm.be:443 "POST /token HTTP/1.1" 400 127
2023-11-05 22:38:15.192 T:1138     info <general>: [plugin.video.vtm.go] [resources.lib.vtmgo.util] Got response (status=400): {"error_description":"[A242307] The device authorization request has not been authorized yet.","error":"authorization_pending"}
2023-11-05 22:38:17.193 T:1138     info <general>: [plugin.video.vtm.go] [resources.lib.vtmgo.util] Sending POST https://login2.vtm.be/token: {'device_code': 'avuCgrEy0iu2VtqYqgCKqvuZcD-QoM1NDFRzVmw--v8', 'client_id': 'vtm-go-androidtv', 'grant_type': 'urn:ietf:params:oauth:grant-type:device_code'}
2023-11-05 22:38:17.196 T:1138     info <general>: [plugin.video.vtm.go] [urllib3.connectionpool] Resetting dropped connection: login2.vtm.be
2023-11-05 22:38:17.416 T:1138     info <general>: [plugin.video.vtm.go] [urllib3.connectionpool] https://login2.vtm.be:443 "POST /token HTTP/1.1" 400 127
2023-11-05 22:38:17.417 T:1138     info <general>: [plugin.video.vtm.go] [resources.lib.vtmgo.util] Got response (status=400): {"error_description":"[A242307] The device authorization request has not been authorized yet.","error":"authorization_pending"}
2023-11-05 22:38:19.418 T:1138     info <general>: [plugin.video.vtm.go] [resources.lib.vtmgo.util] Sending POST https://login2.vtm.be/token: {'device_code': 'avuCgrEy0iu2VtqYqgCKqvuZcD-QoM1NDFRzVmw--v8', 'client_id': 'vtm-go-androidtv', 'grant_type': 'urn:ietf:params:oauth:grant-type:device_code'}
2023-11-05 22:38:19.422 T:1138     info <general>: [plugin.video.vtm.go] [urllib3.connectionpool] Resetting dropped connection: login2.vtm.be
2023-11-05 22:38:19.664 T:1138     info <general>: [plugin.video.vtm.go] [urllib3.connectionpool] https://login2.vtm.be:443 "POST /token HTTP/1.1" 400 127
2023-11-05 22:38:19.665 T:1138     info <general>: [plugin.video.vtm.go] [resources.lib.vtmgo.util] Got response (status=400): {"error_description":"[A242307] The device authorization request has not been authorized yet.","error":"authorization_pending"}
2023-11-05 22:38:21.666 T:1138     info <general>: [plugin.video.vtm.go] [resources.lib.vtmgo.util] Sending POST https://login2.vtm.be/token: {'device_code': 'avuCgrEy0iu2VtqYqgCKqvuZcD-QoM1NDFRzVmw--v8', 'client_id': 'vtm-go-androidtv', 'grant_type': 'urn:ietf:params:oauth:grant-type:device_code'}
2023-11-05 22:38:21.672 T:1138     info <general>: [plugin.video.vtm.go] [urllib3.connectionpool] Resetting dropped connection: login2.vtm.be
2023-11-05 22:38:21.993 T:1138     info <general>: [plugin.video.vtm.go] [urllib3.connectionpool] https://login2.vtm.be:443 "POST /token HTTP/1.1" 400 127
2023-11-05 22:38:21.994 T:1138     info <general>: [plugin.video.vtm.go] [resources.lib.vtmgo.util] Got response (status=400): {"error_description":"[A242307] The device authorization request has not been authorized yet.","error":"authorization_pending"}
2023-11-05 22:38:23.995 T:1138     info <general>: [plugin.video.vtm.go] [resources.lib.vtmgo.util] Sending POST https://login2.vtm.be/token: {'device_code': 'avuCgrEy0iu2VtqYqgCKqvuZcD-QoM1NDFRzVmw--v8', 'client_id': 'vtm-go-androidtv', 'grant_type': 'urn:ietf:params:oauth:grant-type:device_code'}
2023-11-05 22:38:23.998 T:1138     info <general>: [plugin.video.vtm.go] [urllib3.connectionpool] Resetting dropped connection: login2.vtm.be
2023-11-05 22:38:24.559 T:1138     info <general>: [plugin.video.vtm.go] [urllib3.connectionpool] https://login2.vtm.be:443 "POST /token HTTP/1.1" 400 127
2023-11-05 22:38:24.561 T:1138     info <general>: [plugin.video.vtm.go] [resources.lib.vtmgo.util] Got response (status=400): {"error_description":"[A242307] The device authorization request has not been authorized yet.","error":"authorization_pending"}
2023-11-05 22:38:26.561 T:1138     info <general>: [plugin.video.vtm.go] [resources.lib.vtmgo.util] Sending POST https://login2.vtm.be/token: {'device_code': 'avuCgrEy0iu2VtqYqgCKqvuZcD-QoM1NDFRzVmw--v8', 'client_id': 'vtm-go-androidtv', 'grant_type': 'urn:ietf:params:oauth:grant-type:device_code'}
2023-11-05 22:38:26.564 T:1138     info <general>: [plugin.video.vtm.go] [urllib3.connectionpool] Resetting dropped connection: login2.vtm.be
2023-11-05 22:38:26.838 T:1138     info <general>: [plugin.video.vtm.go] [urllib3.connectionpool] https://login2.vtm.be:443 "POST /token HTTP/1.1" 200 1634
2023-11-05 22:38:26.840 T:1138     info <general>: [plugin.video.vtm.go] [resources.lib.vtmgo.util] Got response (status=200): {"access_token":"eyJhbGciOiJSUzI1NiIsInR5cCI6ImF0K2p3dCIsImtpZCI6IjIwMjItMDgtMDUtYXQifQ.eyJzdWIiOiJjNDllNTdiZC05YjE1LTQ2ZjQtYjQxNS0wMTU4OTI4ZTU0M2MiLCJncmFudF90eXBlIjoidXJuOmlldGY6cGFyYW1zOm9hdXRoOmdyYW50LXR5cGU6ZGV2aWNlX2NvZGUiLCJzY29wZSI6bnVsbCwiaXNzIjoiaHR0cHM6Ly9sb2dpbi5wZXJzZ3JvZXAubmV0Iiwic2Vzc2lvbklkIjoiZDY5YTMzY2ItZjg5Yi00OGI2LWE3OTAtMmI3NmQwNWM1ODBkIiwiZXhwIjoxNjk5MjQ5MTA2LCJpYXQiOjE2OTkyMjAzMDYsImNsaWVudF9pZCI6InZ0bS1nby1hbmRyb2lkdHYiLCJqdGkiOiJGX1BwQlFkTGtHNVhyUmZNSERQVEFXclo3Nm1PVUtKT3VVWU9nNmNYQzdzIn0.h7FKXREDUAANqjvcHPMB1Bj1vaeNwWIbxTN8kmMz48JfGm9-hQdzd14dgKqafdZQ54kOwg7qmYwUdZj7QT_T5Y6K3vOdsHPEe77T2PPmTgCR7EhJ3cAgBDutEEEMbfU3-NTs6-8p4ecHDeY2cUDXWP8eB4c0OOW1wDFqPjvTAAwwHHj9ihNw5hIaVrZOYC0S-kgsZENOmUg3WEcMlPhfxsXEZDMzC08q3mLZZCKYNiyowXaAQFKMVMNeTpgion8g98kdBXQvX1JbvdRigVEDuS8ljAWLcIScCZ2J_vFowbm9Fg29B9wevsoR2dlhLVDijOUys4GmpG51mZ3S6LdTWw","refresh_token":"EzRhuCqfjSq08Xc_Du7pwQEOtwJ8eRpMhARINCYXR7A","scope":null,"sessionId":"d69a33cb-f89b-48b6-a790-2b76d05c580d","token_type":"Bearer","expires_in"
2023-11-05 22:38:26.841 T:1138     info <general>: [plugin.video.vtm.go] [resources.lib.vtmgo.util] Sending POST https://lfvp-api.dpgmedia.net/VTM_GO/tokens: {'device': {'id': '1302694e-a732-45f2-a9ed-ab972beb8d0f', 'name': 'VTM Go Addon on Kodi'}, 'idToken': 'eyJhbGciOiJSUzI1NiIsInR5cCI6ImF0K2p3dCIsImtpZCI6IjIwMjItMDgtMDUtYXQifQ.eyJzdWIiOiJjNDllNTdiZC05YjE1LTQ2ZjQtYjQxNS0wMTU4OTI4ZTU0M2MiLCJncmFudF90eXBlIjoidXJuOmlldGY6cGFyYW1zOm9hdXRoOmdyYW50LXR5cGU6ZGV2aWNlX2NvZGUiLCJzY29wZSI6bnVsbCwiaXNzIjoiaHR0cHM6Ly9sb2dpbi5wZXJzZ3JvZXAubmV0Iiwic2Vzc2lvbklkIjoiZDY5YTMzY2ItZjg5Yi00OGI2LWE3OTAtMmI3NmQwNWM1ODBkIiwiZXhwIjoxNjk5MjQ5MTA2LCJpYXQiOjE2OTkyMjAzMDYsImNsaWVudF9pZCI6InZ0bS1nby1hbmRyb2lkdHYiLCJqdGkiOiJGX1BwQlFkTGtHNVhyUmZNSERQVEFXclo3Nm1PVUtKT3VVWU9nNmNYQzdzIn0.h7FKXREDUAANqjvcHPMB1Bj1vaeNwWIbxTN8kmMz48JfGm9-hQdzd14dgKqafdZQ54kOwg7qmYwUdZj7QT_T5Y6K3vOdsHPEe77T2PPmTgCR7EhJ3cAgBDutEEEMbfU3-NTs6-8p4ecHDeY2cUDXWP8eB4c0OOW1wDFqPjvTAAwwHHj9ihNw5hIaVrZOYC0S-kgsZENOmUg3WEcMlPhfxsXEZDMzC08q3mLZZCKYNiyowXaAQFKMVMNeTpgion8g98kdBXQvX1JbvdRigVEDuS8ljAWLcIScCZ2J_vFowbm9Fg29B9wevsoR2dlhLVDijOUys4GmpG51mZ3S6LdTWw'}
2023-11-05 22:38:26.849 T:1138     info <general>: [plugin.video.vtm.go] [urllib3.connectionpool] Starting new HTTPS connection (1): lfvp-api.dpgmedia.net:443
2023-11-05 22:38:27.133 T:1138     info <general>: [plugin.video.vtm.go] [urllib3.connectionpool] https://lfvp-api.dpgmedia.net:443 "POST /VTM_GO/tokens HTTP/1.1" 426 0
2023-11-05 22:38:27.134 T:1138     info <general>: [plugin.video.vtm.go] [resources.lib.vtmgo.util] Got response (status=426): 
2023-11-05 22:38:27.151 T:1138    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'requests.exceptions.HTTPError'>
                                                   Error Contents: 426 Client Error: Upgrade Required for url: https://lfvp-api.dpgmedia.net/VTM_GO/tokens
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.vtm.go/addon_entry.py", line 19, in <module>
                                                       run(argv)
                                                     File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/addon.py", line 186, in run
                                                       routing.run(params)
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/addon.py", line 25, in index
                                                       show_login_menu()
                                                     File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/addon.py", line 39, in show_login_menu
                                                       Authentication().login()
                                                     File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/modules/authentication.py", line 49, in login
                                                       check = self._auth.authorize_check()
                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/vtmgo/vtmgoauth.py", line 121, in authorize_check
                                                       response = util.http_post('https://lfvp-api.dpgmedia.net/VTM_GO/tokens', data={
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/vtmgo/util.py", line 77, in http_post
                                                       return _request('POST', url=url, params=params, form=form, data=data, token=token, profile=profile, headers=headers)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/vtmgo/util.py", line 184, in _request
                                                       response.raise_for_status()
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/models.py", line 1021, in raise_for_status
                                                       raise HTTPError(http_error_msg, response=self)
                                                   requests.exceptions.HTTPError: 426 Client Error: Upgrade Required for url: https://lfvp-api.dpgmedia.net/VTM_GO/tokens
                                                   -->End of Python script error report<--
                                                   
2023-11-05 22:38:27.278 T:1137    error <general>: GetDirectory - Error getting plugin://plugin.video.vtm.go/
2023-11-05 22:38:27.283 T:1025    error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vtm.go/) failed

**System**
 - Addon version: 1.4.2+matrix.1
 - Kodi version: 11.4.1
 - Inputstream adaptive version: 20.3.14.1
 - Operating System (Windows / Mac OS / Android / LibreElec / OSMC / ...): LibreELEC
 - Special Hardware (RPI / Vero4K+ / ...): RPI4

**Additional context**
Stopped working on 5 NOV 2023

2023-11-05 22:37:04.257 T:1025     info <general>: Starting Kodi (20.1 (20.1.0) Git:20.1-Nexus). Platform: Linux ARM 32-bit
2023-11-05 22:37:04.257 T:1025     info <general>: Using Release Kodi x32
2023-11-05 22:37:04.257 T:1025     info <general>: Kodi compiled 2023-03-18 by GCC 12.2.0 for Linux ARM 32-bit version 6.1.19 (393491)
2023-11-05 22:37:04.257 T:1025     info <general>: Running on BCM2835 with LibreELEC (official): 11.0.1, kernel: Linux ARM 64-bit version 6.1.19
2023-11-05 22:37:04.257 T:1025     info <general>: FFmpeg version/source: 4.4.1-Kodi
2023-11-05 22:37:04.257 T:1025     info <general>: 4 CPU cores available
2023-11-05 22:37:04.257 T:1025     info <general>: ARM Features: Neon enabled

2023-11-05 22:37:04.887 T:1025     info <general>: CAddonMgr::FindAddons: inputstream.adaptive v20.3.14.1 installed
2023-11-05 22:37:04.887 T:1025     info <general>: CAddonMgr::FindAddons: inputstream.ffmpegdirect v20.5.0.5 installed
2023-11-05 22:37:04.887 T:1025     info <general>: CAddonMgr::FindAddons: inputstream.rtmp v20.3.0.5 installed

**Comment by esjay90** [comment]
I zee you are running version 1.4.2. There has already been made an update, v 1.4.3. 
You have to wait until this has passed all the checks before the addon will update automatically or you can download and install it manually.

**Comment by Proj3ctS** [comment]
Thanks for the quick reply and sorry for not thoroughly checking the latest version. I have downloaded and installed the version 1.4.3 and it works again.

**Comment by Borromini** [comment]
Thanks, manually installing the 1.4.3 zip fixes it here as well.
