### ISSUE TITLE
VTM Go not launching

### ISSUE THREAD

**Issue by M0nty99** [add-ons/plugin.video.vtm.go#371]
**Describe the bug**
When starting VTM, an error is presented: VTM GO has encountered an error.

**To Reproduce**
1.Start VTM GO

**Logs**
Add debug logs to help troubleshoot the issue. See https://kodi.wiki/view/Log_file/Easy for more info.

https://paste.kodi.tv/izipotapay.kodi
I found following, possibly related errors:
2023-11-08 19:56:21.775 T:4334    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'requests.exceptions.HTTPError'>
                                                   Error Contents: 426 Client Error: Upgrade Required for url: https://lfvp-api.dpgmedia.net/VTM_GO/tokens
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.vtm.go/addon_entry.py", line 19, in <module>
                                                       run(argv)
                                                     File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/addon.py", line 186, in run
                                                       routing.run(params)
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/addon.py", line 25, in index
                                                       show_login_menu()
                                                     File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/addon.py", line 39, in show_login_menu
                                                       Authentication().login()
                                                     File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/modules/authentication.py", line 49, in login
                                                       check = self._auth.authorize_check()
                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/vtmgo/vtmgoauth.py", line 121, in authorize_check
                                                       response = util.http_post('https://lfvp-api.dpgmedia.net/VTM_GO/tokens', data={
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/vtmgo/util.py", line 77, in http_post
                                                       return _request('POST', url=url, params=params, form=form, data=data, token=token, profile=profile, headers=headers)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/vtmgo/util.py", line 184, in _request
                                                       response.raise_for_status()
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/models.py", line 1021, in raise_for_status
                                                       raise HTTPError(http_error_msg, response=self)
                                                   requests.exceptions.HTTPError: 426 Client Error: Upgrade Required for url: https://lfvp-api.dpgmedia.net/VTM_GO/tokens
                                                   -->End of Python script error report<--
**System**
 - Addon version: 1.4.2+matrix.1
 - Kodi version: 20.02 (libreelec 11.0.3)
 - Inputstream adaptive version: 20.3.14.1
 - Operating System: Libreelec
 - Special Hardware (RPI / Vero4K+ / ...): Nuc with Intel N200, 16GB, 1TB SSD

**Additional context**
Issues first noticed 7/11/23 in the evening

**Comment by davidbe** [comment]
There's a new version - 1.4.3 - which handles the recent issues of VTMGo not starting. Try to upgrade, maybe install zip-file manually.

**Comment by M0nty99** [comment]
Thanks for the fast reply, I tried uninstalling and installing again but didn't get 1.4.3. I will try updating with zip file now.
