### ISSUE TITLE
Cannot play VTM programs since yesterday on Kodi Librelec 12 on RPI 5

### ISSUE THREAD

**Issue by trick72** [add-ons/plugin.video.vtm.go#386]
**Describe the bug**
None of the VTM programs are starting with error "cannot start, see log for details"

**To Reproduce**
1. Select any program from VTM, or live TV, or any out of the library
2.
3.

**Expected behavior**

**Screenshots**

**Logs**
2024-06-25 21:36:17.050 T:193738   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'resources.lib.vtmgo.exceptions.InvalidLoginException'>
                                                   Error Contents: 403 Client Error: Forbidden for url: https://videoplayer-service.dpgmedia.net/config/episodes/f74f21f5-2cc7-4b89-a069-9bd285489112?startPosition=0.0&autoPlay=true
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/vtmgo/util.py", line 77, in http_post
                                                       return _request('POST', url=url, params=params, form=form, data=data, token=token, profile=profile, headers=headers)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/vtmgo/util.py", line 184, in _request
                                                       response.raise_for_status()
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/models.py", line 1021, in raise_for_status
                                                       raise HTTPError(http_error_msg, response=self)
                                                   requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://videoplayer-service.dpgmedia.net/config/episodes/f74f21f5-2cc7-4b89-a069-9bd285489112?startPosition=0.0&autoPlay=true
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.vtm.go/addon_entry.py", line 19, in <module>
                                                       run(argv)
                                                     File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/addon.py", line 186, in run
                                                       routing.run(params)
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/addon.py", line 166, in play
                                                       Player().play(category, item)
                                                     File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/modules/player.py", line 56, in play
                                                       resolved_stream = self._stream.get_stream(category, item)
                                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/vtmgo/vtmgostream.py", line 42, in get_stream
                                                       video_info = self._get_video_info(stream_type, stream_id, player_token)
                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/vtmgo/vtmgostream.py", line 162, in _get_video_info
                                                       response = util.http_post(url,
                                                                  ^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/vtmgo/util.py", line 82, in http_post
                                                       raise InvalidLoginException(exc)
                                                   resources.lib.vtmgo.exceptions.InvalidLoginException: 403 Client Error: Forbidden for url: https://videoplayer-service.dpgmedia.net/config/episodes/f74f21f5-2cc7-4b89-a069-9bd285489112?startPosition=0.0&autoPlay=true
                                                   -->End of Python script error report<--
                                                   
2024-06-25 21:36:17.150 T:953     error <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.vtm.go/play/catalog/episodes/f74f21f5-2cc7-4b89-a069-9bd285489112]

**System**
 - Addon version: latest
 - Kodi version:21.0
 - Inputstream adaptive version:latest of date
 - Operating System (Windows / Mac OS / Android / LibreElec / OSMC / ...):RPI 5, LibreElec 12 (latest official)
 - Special Hardware (RPI / Vero4K+ / ...):RPI

**Additional context**

**Comment by davidbe** [comment]
I encountered the same issue: from 2024-06-24, the addon vtmgo doesn't play anything. I will try to post error message this evening.
Kodi: OSMC on VeroV

**Comment by bavala3010** [comment]
Same error here.

**Comment by gregv711** [comment]
Also the same error on LibreELEC 11.0.6

**Comment by Clyde72** [comment]
It is also reported as an login issue more recently. Is not client depended but seems server depended. DPG Media must have changed/rerouted/remapped things.
