### ISSUE TITLE
Season value 2024 not supported

### ISSUE THREAD

**Issue by badoneti** [add-ons/plugin.video.vtm.go#391]
**Describe the bug**
Season 2024 not accepted as value

**To Reproduce**
1. Open VTM go (code from api-17 branch)
2. Go to 10 om te zien
3. Select season 2024 gives an error

**Expected behavior**
Season episodes listed

**Logs**
'2024-08-08 20:12:57.900 T:1104    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: 2024
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.vtm.go/addon_entry.py", line 19, in <module>
                                                       run(argv)
                                                     File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/addon.py", line 191, in run
                                                       routing.run(params)
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/addon.py", line 100, in show_catalog_program_season
                                                       Catalog().show_program_season(program, int(season))
                                                     File "/storage/.kodi/addons/plugin.video.vtm.go/resources/lib/modules/catalog.py", line 189, in show_program_season
                                                       seasons = [program_obj.seasons[season]]
                                                                  ~~~~~~~~~~~~~~~~~~~^^^^^^^^
                                                   KeyError: 2024
                                                   -->End of Python script error report<--
2024-08-08 20:12:58.061 T:1110    error <general>: GetDirectory - Error getting plugin://plugin.video.vtm.go/program/program/43f50b00-6098-42c1-acf2-42e6fc9c6dca/2024
2024-08-08 20:12:58.065 T:1035    error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vtm.go/program/program/43f50b00-6098-42c1-acf2-42e6fc9c6dca/2024) failed'

**Comment by gustav-janssens** [comment]
Can you try clearing the cache? That works for me for similar error messages... You can do so from the addon menu.

**Comment by badoneti** [comment]
Thanks for the hint, clearing cache resolved the issue indeed.
